---
deployment:
  tasks:
    - export BACKEND=/home/vdranjxy/comrades-backend
    - export FRONTEND=/home/vdranjxy/public_html
    - /bin/mkdir -p $BACKEND
    - /bin/cp -a backend/. $BACKEND/
    - /bin/cp -a frontend/dist/. $FRONTEND/
    - /bin/mkdir -p $BACKEND/tmp
    - /bin/touch $BACKEND/tmp/restart.txt
